services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-api2
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - task-management-network

  postgres:
    image: postgres:15-alpine
    container_name: task-management-db2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-management-network

volumes:
  postgres_data:

networks:
  task-management-network:
    driver: bridge